name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Test Server
        run: cd server && npm install && npm test

      - name: Build and Test Client
        run: cd client && npm install && npm test && npm run build
